spring.application.name=smart-campus-operations-hub-api
server.port=8080

spring.datasource.url=jdbc:h2:mem:smartcampusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://root:root@paf.mxvf5hd.mongodb.net/smart-campus-hub?retryWrites=true&w=majority&appName=PAF}
spring.data.mongodb.auto-index-creation=true

app.cors.allowed-origin=${FRONTEND_ORIGIN:http://localhost:5173}
